version: '3'

services:
  nodejs:
    build: .
    command: npm start
    ports:
      - "8000:3333"
    volumes:
      - ./:/usr/src/app
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: my_room
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - "5433:5432"
    volumes:
        - "./src/database/postgres:/var/lib/postgresql/data"



       